name: E2E Tests
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'next'
      - 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    container:
      image: mcr.microsoft.com/playwright:v1.58.1
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        id: build
        run: yarn build
      - name: Run tests
        run: npx allure run -- yarn test:e2e
      - name: Restore Allure history
        if: ${{ steps.build.outcome == 'success' && always() }}
        uses: actions/cache/restore@v4
        with:
          key: allure-history
          path: ./allure-results/history
      - name: Generate test report
        uses: allure-framework/allure-action@v0
        with:
          report-directory: './allure-report'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Save Allure history
        uses: actions/cache/save@v4
        with:
          key: allure-history
          path: ./allure-report/history
      - name: Upload test report
        id: report
        uses: actions/upload-pages-artifact@v3
        with:
          path: './allure-report'
  # Deploy Allure Report to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.report.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to GitHub Pages
        id: report
        uses: actions/deploy-pages@v4
